### ISSUE TITLE
Extract paper URLs from a Mendeley database file

### ISSUE THREAD

**Issue by forrestbao** [forrestbao/autoscholar#2]
Mendeley supports storing the URL information of a paper. We need a Python script to extract the URLs of papers from a Mendeley SQLite database file. The script shall allow the user to specify which folder or group to extract URL from (if not specified, then all papers in the database file). 

The result can be in multiple format, the simplest of which is a CSV file, with paper ID, paper title, paper URL, etc. as the columns. 

For convenience, please also include the path to the PDF file of this paper. If the PDF file is not available (e.g., not yet downloaded to local by the user), just leave the field empty.

**Comment by lihebi** [comment]
The commit (783ef8617a89d137314f173c11043b886b6a3627) should finish downloading htmls from publishers' website

**Comment by forrestbao** [comment]
Hi Hebi, the script you wrote cannot be used by general public. It shall take parameters, e.g., location of SQLlite3 library, the group name (all if not specified), etc. Note that your code is for people to use. Not only for programmers to modify from.

**Comment by lihebi** [comment]
Do you mean (mentioned on README):

```
./webpage.py -g "Group Name" /path/to/db.sqlite
```

There is no hard coded parameters. See the bottom of [webpage.py](https://github.com/forrestbao/autoscholar/blob/mendeley/mendeley/webpage.py)

**Comment by forrestbao** [comment]
1. Some papers were not downloaded properly. 273 and 303. Maybe doi redirect didn't happen correctly. If DOI redirect fails, can we use the value in URL field? It's even safer to use the URLs that user manually entered. I have figured out how to get the URL info.  See the example at the bottom of https://github.com/forrestbao/autoscholar/wiki/Mendeley-database-structure 

2. Could you please move your analysis to Mendeley tables and some SQL commands to that wiki page as well? Let's separate documents and the code in the future. The wiki is a separate git repo, btw.

**Comment by lihebi** [comment]
You can now select `--prefer [doi|url]` to specify which url retrieving method to use when both are available. If only one is available, that one will be used. If neither is available, error will be printed.

A `--output` option is also added to specify output directory. If the html file `<ID>.html` already exists, it will be skipped.

**Comment by forrestbao** [comment]
Thanks. 

1. Could you please check that all papers have correct URLs in the database now? I will use `--prefer url` to download them once and for all. I have only 33 papers as the training sample. So they are all important. 
2. DOI redirect is really not reliable. For paper 297, the redirected page is just the abstract page rather than the full text page. For every paper, please ensure that the URL to the full text page is in URL field.

**Comment by lihebi** [comment]
On my side, there are 40 papers in NSF project. The url fields of them:
- 18 are empty
- 10 are url from http://dx.doi.org
- 12 are urls from publisher website (but not necessary the url to full text). E.g. `http://aem.asm.org/cgi/doi/10.1128/AEM.02708-07` is not full text

I have entered and synced the correct URLs to full text of all documents (to the mendeley server). Check it out.

**Comment by lihebi** [comment]
Some notes for full text and abstract page: Two publishers have separate page for abstract and full text. The redirect will go to the abstract page.
- AEM: add ".full" to the url
  - abstract: http://aem.asm.org/content/78/5/1611
  - full: http://aem.asm.org/content/78/5/1611.full
- wiley: change "abs" to "full"
  - abstract: https://onlinelibrary.wiley.com/doi/abs/10.1002/bit.25021
  - full: https://onlinelibrary.wiley.com/doi/full/10.1002/bit.25021

Thus, there is a function to deal with it:

```python
def full_text_url(url):
    if url.startswith('http://aem.asm.org'):
        return url + '.full'
    elif url.startswith('https://onlinelibrary.wiley.com'):
        return url.replace('abs', 'full')
    else:
        return url
```

The ID on your side seems to be different from my side. Thus, I'm not sure which paper is 297. You can check if it is one of them.

**Comment by forrestbao** [comment]
Thanks. I think `Uuid` shall be universal but it's too hard for human to read. Can you just open the downloaded HTML files for all papers in `NSF project` group to make sure we do get correct full text webpage for them? I know testing is tedious (5 minutes of coding works for 90% of the cases but it will take 1 hour to make it compatible with 95% of the cases). But we have to do it.

**Comment by lihebi** [comment]
I have manually verified all 40 html pages, all of them have correct full paper.
