### ISSUE TITLE
Highlight given sentences in Mendeley 

### ISSUE THREAD

**Issue by forrestbao** [forrestbao/autoscholar#4]
Given a sentence, and the paper that the sentence is from, highlight the sentence in Mendeley, by writing new entries into Mendeley database. 

Do it in Python. The function's arguments can be discussed.

**Comment by lihebi** [comment]
PDF annotator is finished. This version is in racket, and a python version is coming soon. The document is kept at [mendeley/highlight_extract/README.org](https://github.com/forrestbao/autoscholar/blob/mendeley/mendeley/highlight_extract/README.org) for now.

Two new commands are added. It will add highlight to the pattern sentence (permissively, using approximate string matching) into the database, with author "Auto Scholar". Remove command will also remove only highlights with the same author.

```sh
racket cmd.rkt --annotate -g "group name" -d <docId> --pattern "pattern" /path/to/mendeley.sqlite
racket cmd.rkt --remove-annotation
```
