### ISSUE TITLE
transfer <hl> tag to full-text HTML extracts

### ISSUE THREAD

**Issue by forrestbao** [forrestbao/autoscholar#6]
I wasn't smart enough earlier when designing the script [`generate_labeled_data.py
`](../blob/master/preprocessing/generate_labeled_data.py)

There is a much easier way: Just add `<hl>` tags onto the full-text HTML extracted from publisher's website.

Please modify the script (keep functions that are no longer needed but mark them as obsolete in docstring) as follows:
* The input and output remain the same. 
* instead of generating a CSV file, just produce a text file in HTML syntax (HTML forest instead of one HTML tree), such that 
  * each line is one element (a string) of the list `publisher_content` in line 329 of current (as of commit 498aa7c) [`generate_labeled_data.py
`](../blob/498aa7c50aa7123af8dc7b3bfb81fc7605dc20db/preprocessing/generate_labeled_data.py). 
  * and if the line contains highlights, use `<hl>` tags to delimit the highlights.

**Comment by lihebi** [comment]
The commits d33f4dde and 0b0631786c change the output from CSV to html. README is also updated. The result html file is also surrounded with simple `<html><head><style><body>` tags for visualizing purpose.

```html
<html><head><style> hl { background-color: yellow; } </style></head><body>
```
